-- Fase aditiva: no altera saldos existentes ni elimina historial.
CREATE TABLE `tbl_movimiento_financiero` (
  `idmovimiento` INTEGER NOT NULL AUTO_INCREMENT,
  `idmandante` INTEGER NOT NULL,
  `idprestamo` INTEGER NOT NULL,
  `idcliente` INTEGER NOT NULL,
  `tipoMovimiento` VARCHAR(32) NOT NULL,
  `monto` DECIMAL(14,2) NOT NULL,
  `moneda` VARCHAR(3) NOT NULL,
  `montoBase` DECIMAL(14,2) NOT NULL,
  `monedaBase` VARCHAR(3) NOT NULL,
  `tipoCambio` DECIMAL(10,4) NULL,
  `fuenteTipoCambio` VARCHAR(64) NULL,
  `impactoSaldo` DECIMAL(14,2) NOT NULL,
  `saldoAnterior` DECIMAL(14,2) NOT NULL,
  `saldoPosterior` DECIMAL(14,2) NOT NULL,
  `fechaOperacion` DATETIME(3) NOT NULL,
  `fechaRegistro` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `idpago` INTEGER NULL,
  `idacuerdo` INTEGER NULL,
  `idmovimientoOrigen` INTEGER NULL,
  `descripcion` TEXT NULL,
  `motivo` TEXT NULL,
  `creadoPor` INTEGER NULL,
  `aprobadoPor` INTEGER NULL,
  `metadata` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`idmovimiento`),
  INDEX `tbl_movimiento_financiero_idmandante_fechaOperacion_idx` (`idmandante`, `fechaOperacion`),
  INDEX `tbl_movimiento_financiero_idprestamo_fechaOperacion_idx` (`idprestamo`, `fechaOperacion`),
  INDEX `tbl_movimiento_financiero_idpago_idx` (`idpago`),
  INDEX `tbl_movimiento_financiero_tipoMovimiento_createdAt_idx` (`tipoMovimiento`, `createdAt`),
  CONSTRAINT `tbl_movimiento_financiero_idprestamo_fkey`
    FOREIGN KEY (`idprestamo`) REFERENCES `tbl_prestamo`(`idprestamo`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
