import type { CampoCarteraImport, MapeoColumnas } from './types';

/**
 * Columnas reales hoja `data` — archivo base:
 * CARTERA CREDITO PARA COMPRAS 16032026 (1BLOQ).xlsm (CREDICOMPRAS).
 */
export const ALIAS_COLUMNAS: Record<CampoCarteraImport, string[]> = {
  noPrestamo: [
    'noprestamo',
    'n prestamo',
  ],
  codigoUnico: [
    'codigo unico',
    'cod unico',
    'codigo_unico',
  ],
  numerodocumento: [
    'noidentificacion',
    'no identificacion',
    'cedula',
    'identificacion',
    'documento',
  ],
  nombreCliente: [
    'cliente',
    'nombre',
    'nombre completo',
    'nombre cliente',
  ],
  saldoTotal: ['saldototal', 'saldo total', 'saldo', 'saldo actual'],
  diasMora: [
    'diasmoravencimiento',
    'dias mora vencimiento',
    'diasmoracuota',
    'dias mora cuota',
    'dias mora',
    'dias de mora',
    'mora',
  ],
  interesMoratorio: [
    'interesmoratorio',
    'interes moratorio',
    'int moratorio',
    'moratorio',
  ],
  montoPrestamo: [
    'prestamo',
    'monto prestamo',
    'monto del prestamo',
    'capital',
    'monto original',
  ],
  estado: ['estado', 'status', 'estado cuenta'],
  celular: [
    'celularprincipal',
    'celular principal',
    'celular',
    'movil',
    'telefono celular',
  ],
  telefono: ['telefonos', 'telefono', 'tel', 'telefono casa'],
  email: ['correos', 'correo', 'email', 'e mail', 'correo electronico'],
  direccion: ['direccion', 'domicilio', 'dir'],
  noCuenta: ['nocuenta', 'no cuenta', 'cuenta', 'numero cuenta'],
  interes: ['interes corriente'],
  comisionCav: [
    'comision c a v',
    'comision cav',
    'cav',
  ],
  comisionInsitu: ['comision insitu', 'insitu'],
  mantenimientoValor: [
    'mantenimiento valor',
    'mant valor',
    'mantenimiento',
  ],
  gestionCobranza: [
    'gestion de cobranza',
    'gestion cobranza',
    'cargo cobranza',
    'gest cobranza',
  ],
  seguroSvsd: [
    'seguro de vida saldo deudor svsd',
    'seguro svsd',
    'svsd',
    'seguro',
  ],
  cargosAdmin: [
    'cargos administrativos',
    'cargos admin',
    'cargo admin',
  ],
  fechaVencimiento: [
    'fechavencimiento',
    'fecha vencimiento',
    'vencimiento',
  ],
  fechaPrestamo: [
    'fechaprestamo',
    'fecha prestamo',
    'fecha desembolso',
    'fecha otorgamiento',
  ],
  ultimaFechaPago: [
    'ultimafechapago',
    'ultima fecha pago',
    'fecha ultimo pago',
    'ult pago',
  ],
  plazoMeses: ['plazomeses', 'plazo', 'plazo meses', 'plazo en meses'],
  moneda: ['moneda', 'tipo moneda'],
  tipoCambio: ['tipo cambio', 'tc', 'tasa cambio'],
  nombreGestor: ['nombre gestor', 'gestor', 'gestor de ruta'],
  agencia: ['agencia', 'sucursal'],
  ruta: ['ruta'],
  tipoCredito: ['tipocredito', 'tipo credito'],
  modeloPago: ['modelopago', 'modelo pago'],
};

/** Mapeo exacto CREDICOMPRAS — hoja `data` del xlsm base. */
export const MAPEO_CREDICOMPRAS: MapeoColumnas = {
  noPrestamo: 'NoPrestamo',
  codigoUnico: 'CODIGO_UNICO',
  numerodocumento: 'NoIdentificacion',
  nombreCliente: 'Cliente',
  saldoTotal: 'SaldoTotal',
  diasMora: 'DiasMoraVencimiento',
  interesMoratorio: 'InteresMoratorio',
  montoPrestamo: 'Prestamo',
  estado: 'Estado',
  celular: 'CelularPrincipal',
  telefono: 'Telefonos',
  email: 'Correos',
  direccion: 'Direccion',
  noCuenta: 'NoCuenta',
  interes: 'Interes',
  comisionCav: 'Comisión (C.A.V)',
  comisionInsitu: 'Comision Insitu',
  mantenimientoValor: 'Mantenimiento Valor',
  gestionCobranza: 'Gestión de cobranza',
  seguroSvsd: 'Seguro de vida Saldo deudor (SVSD)',
  cargosAdmin: 'Cargos Administrativos',
  fechaVencimiento: 'FechaVencimiento',
  fechaPrestamo: 'FechaPrestamo',
  ultimaFechaPago: 'UltimaFechaPago',
  plazoMeses: 'PlazoMeses',
  nombreGestor: 'NOMBRE GESTOR',
  agencia: 'AGENCIA',
  ruta: 'Ruta',
  tipoCredito: 'TipoCredito',
  modeloPago: 'ModeloPago',
};
